baseurl = "//peidevs.github.io/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = "10"
theme = "mainroad"
title = "PEI Developers"
[[menu.main]]
name = "Github"
url = "https://www.github.com/peidevs"
weight = 5
[[menu.main]]
name = "Twitter"
url = "https://www.twitter.com/peidevs"
weight = 4
[[menu.main]]
name = "Meetup"
url = "https://www.meetup.com/pei-developers"
weight = 3
[[menu.main]]
name = "Code of Conduct"
url = "/code/"
weight = 2
[[menu.main]]
name = "About"
url = "/about/"
weight = 1
[[menu.side]]
name = "Open Data Book Club"
url = "http://peidevs.github.io/OpenDataBookClub/"
weight = 4
[[menu.side]]
name = "Event History"
url = "https://github.com/peidevs/Event_Resources/blob/master/MeetUps.csv"
weight = 4
[[menu.side]]
name = "Request Slack Invite"
url = "https://docs.google.com/forms/d/1hNruzn7fb8Wu7BbuGVvgbeO0-HTNnDrcCJAQ24wZTBs/viewform"
weight = 3
[[menu.side]]
name = "People's Scooter"
url = "https://peidevs.github.io/Event_Resources/"
weight = 2
[[menu.side]]
name = "Scooter"
url = "http://peidevs.github.io/Scooter"
weight = 1
[[menu.side]]
name = "Ladies Learning Code"
url = "http://ladieslearningcode.com/chapters/prince-edward-island/"
weight = 5
[params]
authorbox = false
description = "Home of the PEI Developers Group."
leftsidebar = false
opengraph = false
post_navigation = true
subtitle = "est. 2012"
[params.widgets]
categories = true
important = true
recent_articles = true
recent_articles_num = "5"
search = false
tags = false
tags_counter = false
